### PR TITLE
♻️ refactoring: rename `okp4` by `axone`

### PR DESCRIPTION
**Pull request by bdeneux**
## 📝 Description

This PR prepare the renaming of the chain from `okp4` to `axone`. 

## 📋 Steps : 
- [x] Rename go module
- [x] Rename binary name
- [x] Rename proto import
- [x] Change docker name 
- [x] Regenerate documentation
- [x] Update all reference to okp4 address to an Axone address in tests and comments
- [x] Update license, README and CHANGELOG to the new repository
- [x] Update denom name
- [x] Update all GitHub action workflow secrets naming (e.i: `$OKP4_TOKEN`)

## 📣 External or admin steps 

- [x] `$BUF_TOKEN` used in [publish.yml](https://github.com/okp4/okp4d/blob/fa21817e0e18f348321476efb35fe03a94fd5e89/.github/workflows/publish.yml#L96) should be linked to the buf [okp4 organization](https://buf.build/okp4) and we need to rename it or recreate a new one for axone. `but.yml` configuration follow the same name than GitHub : `buf.build/axone-protocol/axoned` 
- [ ] The same for the docker registry that is named like the GitHub repository : `axone-protocol/axoned` (`$DOCKER_HUB_REGISTRY_TOKEN`, `$DOCKER_HUB_REGISTRY_ID`)
- [x] `$OKP4_TOKEN` should be renamed to `$OPS_TOKEN` and all related organization secrets should be transferred to the new organization. Repository secrets are kept during the transfer : (https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#whats-transferred-with-a-repository)
- [x] OKP4 Bot secrets renaming : 
  - `$OKP4_BOT_GPG_PRIVATE_KEY` --> `$BOT_GPG_PRIVATE_KEY`
  - `$OKP4_BOT_GPG_PASSPHRASE` --> `$BOT_GPG_PASSPHRASE`
  - `$OKP4_BOT_GIT_AUTHOR_NAME` --> `$BOT_GIT_AUTHOR_NAME`
  - `$OKP4_BOT_GIT_AUTHOR_EMAIL` --> `$BOT_GIT_AUTHOR_EMAIL`
  - `$OKP4_BOT_GIT_COMMITTER_NAME` --> `$BOT_GIT_COMMITTER_NAME`
  - `$OKP4_BOT_GIT_COMMITTER_EMAIL` --> `$BOT_GIT_COMMITTER_EMAIL`
- [x] Discord bot secrets also : `$OKP4_DISCORD_WEBHOOK` --> `$DISCORD_WEBHOOK`
- [ ] The README [contains link](https://github.com/okp4/okp4d/blob/main/README.md#query-a-running-network) to the okp4 testnet that should be updated when new axone testnet will be deployed.
- [ ] [CI workflow](https://github.com/okp4/okp4d/pull/616/files#diff-36de11d4f4c4bfde4cd8b252c66727c8ee1ce99eca900e43c34352f4086ee344) that trigger another workflows is linked to the OKP4 organization too, since documentation will be transferred also (I think?), I update the link to the new axone-protocol organization.
- [ ] Variable name in docs should be renamed to axonedVersion : https://github.com/okp4/docs/blob/5d2c59a1767ac0e3ff1850ef7b77b653dc7f88e3/data/chain.json#L2

### CODE REVIEW

**Comment by bdeneux** [comment]
@amimart Is up to you now for the admin steps 😉

**Comment by ccamel** [comment]
Hey @bdeneux, just wanted to let you know that I added a `!` to your latest commit as per the conventional commit spec, to indicate the breaking change introduced by your PR. Also, I've made some updates to align the protocol description with Axone's narrative.

**Comment by amimart** [comment]
I completed the CI & admin steps, here's a sum up:

Secrets change:
- `OKP4_TOKEN` -> `OPS_TOKEN`
- `OKP4_BOT_*` -> `BOT_*`
- `OKP4_DISCORD_WEBHOOK ` -> `DISCORD_WEBHOOK`

All the secrets have been created on the axone organisation except the ones concerning the docker hub publication, the new docker organisation being in the process of creation I just disabled the related image push temporarily.

About the testnet referenced in the readme it is obsolete now, I propose to manage that matter post-migration.

We'll take care of the changes related to docs when we migrate it.

**Review by amimart — APPROVED** [review]

**Review by ccamel — APPROVED** [review]
All good! :+1:

**Pull request merged**
